/* Every word on screen, in English and simple Chinese. t('key', { n: 3 }) fills {n}; a key with '.1' is used when n is 1. */
(function (root) {
  'use strict';
  var EN = {
    'task': 'Piglet processing',
    'last': 'Last record', 'last.none': 'Nothing recorded yet',
    'batch': 'Batch {b}',
    'tr.iron': 'Iron', 'tr.tail': 'Dock tail', 'tr.castrate': 'Castrate', 'tr.cocci': 'Coccidiosis',
    'trl.iron': 'iron', 'trl.tail': 'tail docking', 'trl.castrate': 'castration', 'trl.cocci': 'coccidiosis',
    'sum.due': '{Tr} due today', 'sum.notdone': 'Not done', 'sum.none': 'Due today', 'sum.pens': 'pens', 'sum.pens.1': 'pen', 'sum.nothing': 'nothing due',
    'sum.task': 'Task', 'sum.done': 'pens done', 'sum.end': 'Tap to end the task', 'sum.ended': 'Task ended',
    'lens.todo': 'To do', 'lens.done': 'Done', 'lens.all': 'All',
    'row': 'Row {r}', 'row.pens': '· {n} pens', 'row.pens.1': '· 1 pen',
    'empty.todo': 'Nothing left to do today.', 'empty.done': 'No pen is done yet.',
    'piglets': '{n} piglets', 'piglets.1': '{n} piglet',
    'due.today': 'due today', 'late': 'late', 'early': 'early', 'Late': 'Late', 'Early': 'Early',
    'left': '{n} left', 'why.weak': 'weak', 'why.sick': 'sick', 'why.moved': 'moved in',
    'nothing.due': 'Nothing due today', 'from.day': '{tr} from day {d}', 'all.given': 'All given',
    'done.at': 'done {t}', 'day.n': 'day {d}', 'ended.row': 'Task ended',
    'chip.sow': 'Sow died', 'chip.missing': '{n} missing', 'chip.late': 'Late',
    'dock.bulk': 'Record for several pens',
    'sheet.sub': 'Day {d} · Row {r}',
    'born': 'Born', 'alive': 'Alive now', 'dead': 'Dead',
    'line.sow': 'The sow died.', 'line.missing': '{n} missing after a count.', 'line.out': '{n} moved out.', 'line.in': '{n} moved in.',
    'tool.death': 'Record death', 'tool.move': 'Move', 'tool.count': 'Set count',
    'sec.today': 'Today', 'sec.notgiven': 'Not given', 'sec.done': 'Done', 'sec.coming': 'Coming', 'sec.today.status': 'Day {d}',
    'given.days': 'day {a}–{b}', 'record.n': 'Record {n}',
    'done.meta': '{t} · {who} · {n}', 'coming.meta': 'from day {d}',
    'kept.note': 'yours kept as a note',
    'flash.treat': '{tr} recorded · {n}', 'flash.death': 'Death recorded · {n}', 'flash.move': '{n} moved to {to}', 'flash.count': 'Count set to {n}',
    'undo': 'Undo', 'undone': 'Undone',
    'ended.note': 'Task ended. Nothing more can be recorded.',
    'back': 'Back', 'save': 'Save', 'cancel': 'Cancel', 'done.btn': 'Done', 'ok': 'OK',
    'treat.sub': '{pen} · day {d} · {n} to do', 'treat.given': 'Piglets given', 'treat.why': 'Why fewer?',
    'treat.weak': 'Weak', 'treat.sick': 'Sick', 'treat.later': 'The other {n} stay on the list for later.', 'treat.later.1': 'The other one stays on the list for later.',
    'death.title': 'Record death', 'death.sub': '{pen} · {n} alive', 'c.crushed': 'Crushed', 'c.scours': 'Scours', 'c.starve': 'Starve-out', 'c.other': 'Other',
    'death.missing': 'One of the missing?', 'death.missing.n': 'From the missing ones?', 'no': 'No', 'yes': 'Yes',
    'move.title': 'Move piglets', 'move.sub': 'From {pen} · {n} alive', 'move.to': 'To pen', 'move.how': 'How many', 'move.had': 'Had {tr}?',
    'move.pen.meta': 'day {d} · {n} piglets', 'move.save': 'Move {n}', 'move.pick': 'Pick a pen first',
    'count.title': 'Set count', 'count.sub': '{pen} · was {n}', 'count.label': 'Piglets alive', 'count.unsure': 'Not sure why', 'count.wrong': 'Count was wrong',
    'bulk.title': 'Record for several pens', 'bulk.pick': 'Pick a treatment', 'bulk.pens.now': '{n} pens due now', 'bulk.pens.now.1': '1 pen due now', 'bulk.pens.none': 'none due now',
    'bulk.page': '{tr} · several pens', 'bulk.window': 'Given on day {a}–{b}', 'g.now': 'Due now', 'g.early': 'Too early', 'g.late': 'Late', 'g.done': 'Done',
    'bulk.hold': 'Record {tr} · {p} · {n}', 'pens.n': '{n} pens', 'pens.n.1': '1 pen', 'bulk.caption': 'HOLD TO RECORD', 'bulk.none': 'Tick at least one pen',
    'bulk.left': '{n} left · {why}',
    'confirm.title': 'Record anyway?', 'confirm.text': '{pen} is day {d}. {Tr} is given on day {a}–{b}. It will be marked {mark}.', 'confirm.ok': 'Record anyway',
    'receipt.title': '{Tr} recorded', 'receipt.line': '{p} · {n}', 'receipt.meta': '{t} · {who}',
    'end.title': 'End task', 'end.sub': 'Piglet processing · Batch {b}', 'end.count': '{d} of {n} pens done', 'end.not': '{n} pens not done', 'end.not.1': '1 pen not done', 'end.all': 'All pens done',
    'end.notdone': 'Not done', 'end.coming': 'Not due yet in {n} pens: {list}. Ending the task stops these too.', 'end.coming.1': 'Not due yet in 1 pen: {list}. Ending the task stops this too.',
    'end.hold': 'End task', 'end.caption': 'HOLD TO END', 'end.done.title': 'Task ended', 'end.done.line': 'Piglet processing ended',
    'not.given': '{tr} not given', 'not.given.list': 'Not given: {list}',
    'note.clash': '{Tr} for {pen} was already recorded by {who} at {t}. Yours is kept as a note.',
    'note.arrived': '{who}\'s phone recorded {tr} on {pen} at {t}.',
    'demo.lang': 'Language', 'demo.reset': 'Reset demo', 'demo.open': 'Demo', 'demo.other': 'Demo: another phone recorded iron on A05',
    'demo.tip': 'To see two phones clash, record iron on A05 on this phone first.',
    'demo.again': 'The other phone\'s record is already here.', 'demo.ended': 'The task has ended.',
    'yesterday': 'yesterday'
  };
  var ZH = {
    'task': '仔猪处理',
    'last': '最近记录', 'last.none': '还没有记录',
    'batch': '第{b}批',
    'tr.iron': '补铁', 'tr.tail': '断尾', 'tr.castrate': '去势', 'tr.cocci': '防球虫',
    'trl.iron': '补铁', 'trl.tail': '断尾', 'trl.castrate': '去势', 'trl.cocci': '防球虫',
    'sum.due': '今天要{Tr}', 'sum.notdone': '没做完', 'sum.none': '今天要做', 'sum.pens': '栏', 'sum.pens.1': '栏', 'sum.nothing': '今天没有',
    'sum.task': '任务', 'sum.done': '栏已做完', 'sum.end': '点这里结束任务', 'sum.ended': '任务已结束',
    'lens.todo': '待做', 'lens.done': '做完', 'lens.all': '全部',
    'row': '{r}排', 'row.pens': '· {n}栏',
    'empty.todo': '今天没有要做的了。', 'empty.done': '还没有做完的栏。',
    'piglets': '{n}头', 'piglets.1': '{n}头',
    'due.today': '今天做', 'late': '晚了', 'early': '提前', 'Late': '晚了', 'Early': '提前',
    'left': '还剩{n}头', 'why.weak': '太弱', 'why.sick': '生病', 'why.moved': '转进来的',
    'nothing.due': '今天没有要做的', 'from.day': '{tr}第{d}天做', 'all.given': '全部做完',
    'done.at': '{t}做完', 'day.n': '第{d}天', 'ended.row': '任务已结束',
    'chip.sow': '母猪死了', 'chip.missing': '少{n}头', 'chip.late': '晚了',
    'dock.bulk': '多栏一起记录',
    'sheet.sub': '第{d}天 · {r}排',
    'born': '出生', 'alive': '现在活着', 'dead': '死亡',
    'line.sow': '母猪死了。', 'line.missing': '清点后少了{n}头。', 'line.out': '转出{n}头。', 'line.in': '转进{n}头。',
    'tool.death': '记录死亡', 'tool.move': '转栏', 'tool.count': '改头数',
    'sec.today': '今天', 'sec.notgiven': '没做的', 'sec.done': '做完的', 'sec.coming': '以后做', 'sec.today.status': '第{d}天',
    'given.days': '第{a}–{b}天', 'record.n': '记录{n}头',
    'done.meta': '{t} · {who} · {n}', 'coming.meta': '第{d}天开始',
    'kept.note': '你的记录留作备注',
    'flash.treat': '已记录{tr} · {n}', 'flash.death': '已记录死亡 · {n}', 'flash.move': '{n}转到{to}', 'flash.count': '头数改为{n}',
    'undo': '撤销', 'undone': '已撤销',
    'ended.note': '任务已结束，不能再记录。',
    'back': '返回', 'save': '保存', 'cancel': '取消', 'done.btn': '完成', 'ok': '知道了',
    'treat.sub': '{pen} · 第{d}天 · 要做{n}', 'treat.given': '做了几头', 'treat.why': '为什么少了？',
    'treat.weak': '太弱', 'treat.sick': '生病', 'treat.later': '剩下的{n}头留到以后做。', 'treat.later.1': '剩下的1头留到以后做。',
    'death.title': '记录死亡', 'death.sub': '{pen} · 活着{n}', 'c.crushed': '压死', 'c.scours': '拉稀', 'c.starve': '饿死', 'c.other': '其他',
    'death.missing': '是少的那头吗？', 'death.missing.n': '是少的那几头吗？', 'no': '不是', 'yes': '是',
    'move.title': '转栏', 'move.sub': '从{pen}转出 · 活着{n}', 'move.to': '转到哪栏', 'move.how': '转几头', 'move.had': '做过{tr}吗？',
    'move.pen.meta': '第{d}天 · {n}', 'move.save': '转{n}', 'move.pick': '先选一个栏',
    'count.title': '改头数', 'count.sub': '{pen} · 原来{n}头', 'count.label': '活着的仔猪', 'count.unsure': '不知道为什么', 'count.wrong': '之前数错了',
    'bulk.title': '多栏一起记录', 'bulk.pick': '选一项处理', 'bulk.pens.now': '现在{n}栏要做', 'bulk.pens.now.1': '现在1栏要做', 'bulk.pens.none': '现在没有要做的',
    'bulk.page': '{tr} · 多栏', 'bulk.window': '第{a}–{b}天做', 'g.now': '现在做', 'g.early': '太早', 'g.late': '晚了', 'g.done': '做完',
    'bulk.hold': '记录{tr} · {p} · {n}', 'pens.n': '{n}栏', 'pens.n.1': '1栏', 'bulk.caption': '按住记录', 'bulk.none': '至少勾一栏',
    'bulk.left': '还剩{n}头 · {why}',
    'confirm.title': '还是要记录？', 'confirm.text': '{pen}是第{d}天。{Tr}应在第{a}–{b}天做。会标为“{mark}”。', 'confirm.ok': '还是记录',
    'receipt.title': '{Tr}已记录', 'receipt.line': '{p} · {n}', 'receipt.meta': '{t} · {who}',
    'end.title': '结束任务', 'end.sub': '仔猪处理 · 第{b}批', 'end.count': '{n}栏中{d}栏做完', 'end.not': '{n}栏没做完', 'end.not.1': '1栏没做完', 'end.all': '全部做完',
    'end.notdone': '没做完', 'end.coming': '还有{n}栏没到时间：{list}。结束任务后这些也不做了。', 'end.coming.1': '还有1栏没到时间：{list}。结束任务后这些也不做了。',
    'end.hold': '结束任务', 'end.caption': '按住结束', 'end.done.title': '任务已结束', 'end.done.line': '仔猪处理已结束',
    'not.given': '没有{tr}', 'not.given.list': '没做：{list}',
    'note.clash': '{pen}的{tr}已经由{who}在{t}记录了。你的记录留作备注。',
    'note.arrived': '{who}的手机在{t}记录了{pen}的{tr}。',
    'demo.lang': '语言', 'demo.reset': '重置演示', 'demo.open': '演示', 'demo.other': '演示：另一部手机记录了A05补铁',
    'demo.tip': '想看两部手机冲突：先在这部手机上记录A05的补铁。',
    'demo.again': '另一部手机的记录已经在了。', 'demo.ended': '任务已结束。',
    'yesterday': '昨天'
  };
  var DICT = { en: EN, zh: ZH }, lang = 'en';
  try { lang = localStorage.getItem('pp-simple-lang') === 'zh' ? 'zh' : 'en'; } catch (e) { /* default en */ }
  function t(key, a) {
    var d = DICT[lang], n = a && a.n;
    var s = (n === 1 || n === '1') && d[key + '.1'] != null ? d[key + '.1'] : d[key];
    if (s == null) s = EN[key] != null ? EN[key] : key;
    return s.replace(/\{(\w+)\}/g, function (m, k) { return a && a[k] != null ? a[k] : m; });
  }
  function setLang(l) { lang = l === 'zh' ? 'zh' : 'en'; try { localStorage.setItem('pp-simple-lang', lang); } catch (e) { /* not kept */ } }
  root.PPT = { t: t, setLang: setLang, get lang() { return lang; }, EN: EN, ZH: ZH };
})(globalThis);
